### ISSUE TITLE
Handshifts

### ISSUE THREAD

**Issue by samosafuz** [jcowey/P3#13]
Holger's article includes handshifts, which appear to have been garbled at some point:

See [l. 158](https://github.com/jcowey/P3/blob/27615c1435a8a83aaa83412a7d7bac12589820ee/pylon/pylon1essler/essler_pBerol_inv_13264.xml#L158).

`<lb n="123"/><supplied reason="lost">ἐκτὸς ὁδοῦ, μή πώ τις ὁδιτ</supplied><unclear>άω</unclear>ν <add place="above">m<gap reason="illegible" quantity="2" unit="character"/> <supplied reason="lost">ὁδοι</supplied>πόρων</add> m<gap reason="illegible" quantity="1" unit="character"/> ἀνθρώπων,<g type="middot"/>`

I wonder whether this is an issue with Hugh's converter program. These aren't illegible letters, but hand indicators.

**Comment by jcowey** [comment]
Corrected directly. No it was not conversion program problem. I had failed to spot incorrect Leiden+.

`m.2` instead of `$m2`
